### ISSUE TITLE
submit to PypI and https://www.djangopackages.com/grids/g/model-audit/

### ISSUE THREAD

**Issue by urijah** [TriplePoint-Software/audit_trail#4]
also need a better name. django-audit-trail ?

**Comment by syabro** [comment]
Already at pypi by the name audit-trail. But yeah, django-audit-trail is better to discover

**Comment by syabro** [comment]
Updated pypi
https://pypi.python.org/pypi/django_audit_trail/0.0.23

**Comment by syabro** [comment]
Added to 
https://www.djangopackages.com/grids/g/model-audit/
https://www.djangopackages.com/packages/p/django_audit_trail/
